apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-backend-depl
  labels:
    type: bank-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: bank
      language: java
  template:
    metadata:
      labels:
        type: backend
        service: bank
        language: java
    spec:
      containers:
        - name: bank-backend
          image: public.ecr.aws/h7c9d4d9/demo-bank-service:latest
          env:
            - name: JAEGER_ENDPOINT
              value: 'http://host.docker.internal:14250'
            - name: JAEGER_ENABLED
              value: 'true'
            - name: DB_USER
              value: 'paymentuser'
            - name: DB_NAME
              value: 'bankdb'
            - name: DB_PASSWORD
              value: 'db@password'
          # imagePullPolicy: Never
          ports:
            - containerPort: 9001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-backend-depl
  labels:
    type: fraud-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: fraud
      language: java
  template:
    metadata:
      labels:
        type: backend
        service: fraud
        language: java
    spec:
      containers:
        - name: fraud-backend
          image: public.ecr.aws/h7c9d4d9/demo-fraud-service:latest
          env:
            - name: JAEGER_ENDPOINT
              value: 'http://host.docker.internal:14250'
            - name: JAEGER_ENABLED
              value: 'true'
          # imagePullPolicy: Never
          ports:
            - containerPort: 9002
