deployment:

  paymentBackend:
    name: 'payment-backend-api'
    image: 'demo_payment-service'
    tag: 'latest'
    port: 8888
    replicas: 2

  db:
    name: 'payment-db'
    port: 5432

  downstream:
    bank:
      name: 'bank-backend-api'
      image: 'public.ecr.aws/h7c9d4d9/demo-bank-service:latest'
      port: 9001
    fraud:
      name: 'fraud-backend-api'
      image: 'public.ecr.aws/h7c9d4d9/demo-fraud-service:latest'
      port: 9002



service:

  paymentBackend:
    name: 'payment-backend-svc'
    port: 8888

  db:
    name: 'payment-db-svc'
    port: 5432

  downstream:
    bank:
      name: 'bank-backend-svc'
      port: 9001
    fraud:
      name: 'fraud-backend-svc'
      port: 9002



