apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.downstream.bank.name}}
  # labels:
  #   type: bank-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: {{.Values.deployment.downstream.bank.name}}
      language: java
  template:
    metadata:
      labels:
        type: backend
        service: {{.Values.deployment.downstream.bank.name}}
        language: java
    spec:
      containers:
        - name: bank-backend
          image: {{.Values.deployment.downstream.bank.image}}
          env:
            - name: JAEGER_ENDPOINT
              value: 'http://host.docker.internal:14250'
            - name: JAEGER_ENABLED
              value: 'true'
            - name: DB_USER
              value: 'paymentuser'
            - name: DB_NAME
              value: 'bankdb'
            - name: DB_PASSWORD
              value: 'db@password'
          # imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.deployment.downstream.bank.port}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.downstream.fraud.name}}
  # labels:
  #   type: fraud-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      type: backend
      service: {{.Values.deployment.downstream.fraud.name}}
      language: java
  template:
    metadata:
      labels:
        type: backend
        service: {{.Values.deployment.downstream.fraud.name}}
        language: java
    spec:
      containers:
        - name: fraud-backend
          image: {{.Values.deployment.downstream.fraud.image}}
          env:
            - name: JAEGER_ENDPOINT
              value: 'http://host.docker.internal:14250'
            - name: JAEGER_ENABLED
              value: 'true'
          # imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.deployment.downstream.fraud.port}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.downstream.bank.name}}
spec:
  type: ClusterIP
  selector:
    type: backend
    service: {{.Values.deployment.downstream.bank.name}}
    language: java
  ports:
    - port: {{.Values.service.downstream.bank.port}}
      targetPort: {{.Values.deployment.downstream.bank.port}} #exposed port from the pod
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.downstream.fraud.name}}
spec:
  type: ClusterIP
  selector:
    type: backend
    service: {{.Values.deployment.downstream.fraud.name}}
    language: java
  ports:
    - port: {{.Values.service.downstream.fraud.port}}
      targetPort: {{.Values.deployment.downstream.fraud.port}} #exposed port from the pod
      protocol: TCP
